name: build and deployment

on: [push]

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
    - name: Build
      run: |
        sudo apt install shc tree -y
        chmod +x build
        bash build
    - name: config
      env:
        BUCKET: ${{ secrets.COS_BUCKET_NAME }}
        SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        REGION: ap-tokyo
      run: |
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        tccli configure set secretId $SECRET_ID
        tccli configure set secretKey $SECRET_KEY
        tccli configure set region $REGION
    - name: deployment
      run: |
        coscmd upload -rfs --delete ./* /
        tccli PurgePathCache --cli-unfold-argument --Paths https://shell-builder.init.ac/ --FlushType flush