name: build and deployment

on: [push]

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
    - name: 依赖安装
      run: |
        sudo apt install shc tree -y
        sudo pip install tccli
        sudo pip install https://github.com/tencentyun/coscmd/archive/refs/heads/master.zip
    - name: 执行构建
      run: |
        chmod +x build
        bash build
    - name: 仓库配置
      env:
        BUCKET: ${{ secrets.COS_BUCKET_NAME }}
        SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        REGION: ap-tokyo
      run: |
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        tccli configure set secretId $SECRET_ID
        tccli configure set secretKey $SECRET_KEY
        tccli configure set region $REGION
    - name: 制品部署
      run: |
        for dirs in `ls |grep -Ev 'README.md|LICENSE|build'`;do
          coscmd upload -rfs --delete ./${dirs} /
        done
        tccli PurgePathCache --cli-unfold-argument --Paths https://shell-builder.init.ac/ --FlushType flush